### PR TITLE
[SENTINEL] Add telemetry

### PR DESCRIPTION
**Pull request by ngmachado**
This PR adds telemetry features to Sentinel.

Objective: Continue to work on data collection to help future development of sentinel network.

- Option to opt-out (don't share data with Superfluid)
- Option to configure a new URL endpoint allowing Sentinel Operator to analyse data.
- Light weight process (every 12hours)
- Data collected: Full Report (no private data is send)

### CODE REVIEW

**Comment by vmichalik** [comment]
any reason to leave this hanging?

**Review by d10r — CHANGES_REQUESTED** [review]
Missing:
* Document the new config options
* Set up a first iteration of a default Telemetry Collector Service which receives and persists the data (can be as simple as writing a json file per request) - or even just define the default URL we can then deploy something to. Proposal: sentinel-telemetry.x.superfluid.dev
* Define some kind of "sentinel id". It should be a unique, immutable identifier which remains stable across restarts. It's different from IP address, liquidator account, process id. Maybe closest relationship is the DB lifetime. We could tie it to [this condition](https://github.com/superfluid-finance/superfluid-sentinel/blob/master/src/app.js#L186) - in the _true_ branch generate a uuid which is persisted in the DB and added as field to reports. So re-syncing would change the uuid (which is imo ok). Possible corner case: DB is copied and also used for another, parallel instance, e.g. with different config/liquidator account. Would that even work? Can we easily mitigate that (avoid two instances reporting the same uuid)?

@ngmachado this is a lot of text, but all doable quite quickly. Lets do a spike together to get this over the line.

**Comment by hellwolf** [comment]
Blocker: missing a backend to continue.

Moving this back to backlog.

**Comment by hellwolf** [comment]
Waiting for momodu to give an assessment that if we have enough ingredients to continue this.

**Review by d10r — APPROVED** [review]

**Comment by d10r** [comment]
completed

**Pull request merged**
