### PR TITLE
GDA Support

### PR DESCRIPTION
**Pull request by hellwolf**

### CODE REVIEW

**Comment by d10r** [comment]
health report seems to not work.
`curl http://solvency-staging.x.superfluid.dev:10005` returns nothing.
(/metrics does).

**Comment by d10r** [comment]
@ngmachado something to be checked: On a staging instance I get an empty response from the report endpoint.

**Comment by ngmachado** [comment]
Hi @d10r thank for the report. I need more information, where is the staging sentinel env running? I need to check the logs.

**Comment by d10r** [comment]
TBD: https://github.com/superfluid-finance/superfluid-sentinel/issues/245

**Review by d10r — APPROVED** [review]
lets go

**Pull request merged**
